repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        additional_dependencies: [ruff>=0.14.8]
        types: [python]
        pass_filenames: true
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: python
        additional_dependencies: [ruff>=0.14.8]
        types: [python]
        pass_filenames: true
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        additional_dependencies: [prettier@^3.2.5]
        types_or: [json, markdown, yaml, javascript]
        pass_filenames: true
